# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - security-thecyberhub-org

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_71eae767d62541aaaa8310df50ecd26d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_14d2df9e1fa74c6ab7ae7097fad55b9c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_71eae767d62541aaaa8310df50ecd26d }}/kabir0x23/thecyberhub.org:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'security-thecyberhub-org'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_46d9529e7f9844b7a044bb81161d198d }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_71eae767d62541aaaa8310df50ecd26d }}/kabir0x23/thecyberhub.org:${{ github.sha }}'